# Generated by Django 5.2.10 on 2026-01-07 02:26

import django.db.models.deletion
import utilities.idx
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyCheckout',
            fields=[
                ('id', models.CharField(default=utilities.idx.generate_checkout_id, editable=False, help_text='An identifier for the checkout session. Default is a {idx.generate_checkout_id}.', max_length=255, primary_key=True, serialize=False)),
                ('unit_amount', models.IntegerField(default=0, help_text='Amount in the smallest currency unit')),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('payment_gateway', models.CharField(choices=[('flutterwave', 'Flutterwave'), ('paystack', 'Paystack')], max_length=100)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('successful', 'Successful'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='initiated', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_checkouts', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_checkouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Checkout',
                'verbose_name_plural': 'Property Checkouts',
                'ordering': ['-created_at'],
            },
        ),
    ]
