# Generated by Django 5.2.11 on 2026-02-24 12:21

import django.db.models.deletion
import utilities.idx
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('properties', '0006_propertychat_allow_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyChatInvoice',
            fields=[
                ('id', models.CharField(default=utilities.idx.generate_checkout_id, editable=False, help_text='An identifier for the checkout session. Default is a {idx.generate_checkout_id}.', max_length=255, primary_key=True, serialize=False)),
                ('unit_amount', models.IntegerField(default=0, help_text='Amount in the smallest currency unit')),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('payment_gateway', models.CharField(choices=[('flutterwave', 'Flutterwave'), ('paystack', 'Paystack')], max_length=100)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('successful', 'Successful'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='initiated', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_sealed', models.BooleanField(default=False)),
                ('possession_period_start_date', models.DateTimeField()),
                ('possession_period_end_date', models.DateTimeField(blank=True, null=True)),
                ('property_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_chat_invoices', to='properties.propertychat')),
            ],
            options={
                'verbose_name': 'Property Chat Invoice',
                'verbose_name_plural': 'Property Chat Invoices',
                'ordering': ['-created_at'],
            },
        ),
    ]
