# Generated by Django 5.2.11 on 2026-02-25 16:14

import utilities.idx
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_propertychatinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertychatinvoice',
            name='id',
            field=models.CharField(default=utilities.idx.generate_invoice_id, editable=False, help_text='An identifier for the invoice. Default is a {idx.generate_invoice_id}.', max_length=255, primary_key=True, serialize=False),
        ),
    ]
