# Generated by Django 5.2.9 on 2025-12-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cognito_uid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
