# Generated by Django 5.2.10 on 2026-02-03 21:16

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostAccountAgent',
            fields=[
                ('hostaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.hostaccount')),
                ('cac_cert_doc', models.ImageField(max_length=255, upload_to=accounts.models.UploadHostAccountHelper('cac_cert_doc'), verbose_name='CAC Certificate Document')),
                ('industry_license', models.ImageField(blank=True, max_length=255, null=True, upload_to=accounts.models.UploadHostAccountHelper('industry_license'), verbose_name='Industry License')),
                ('proof_of_address', models.ImageField(max_length=255, upload_to=accounts.models.UploadHostAccountHelper('proof_of_address'), verbose_name='Proof of Address')),
                ('rep_id', models.ImageField(max_length=255, upload_to=accounts.models.UploadHostAccountHelper('rep_id'), verbose_name='Dir./Authorized Rep. ID Number')),
            ],
            options={
                'verbose_name': 'Agent Host Account',
                'verbose_name_plural': 'Agent Host Accounts',
            },
            bases=('accounts.hostaccount',),
        ),
        migrations.CreateModel(
            name='HostAccountArchitect',
            fields=[
                ('hostaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.hostaccount')),
                ('arcon_reg_no', models.CharField(help_text='ARCON Registration Number for the architect host.', max_length=100, unique=True, verbose_name='ARCON Registration Number')),
                ('practice_license', models.ImageField(max_length=255, upload_to=accounts.models.UploadHostAccountHelper('practice_license'), verbose_name='Practice License')),
                ('govt_issued_id', models.ImageField(max_length=255, upload_to=accounts.models.UploadHostAccountHelper('govt_issued_id'), verbose_name='Government Issued ID')),
                ('ref_phone_no', models.CharField(help_text='Reference Phone Number for the architect host.', max_length=15, verbose_name='Reference Phone Number')),
            ],
            options={
                'verbose_name': "Architect's Host Account",
                'verbose_name_plural': "Architect's Host Accounts",
            },
            bases=('accounts.hostaccount',),
        ),
        migrations.CreateModel(
            name='HostAccountCompany',
            fields=[
                ('hostaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.hostaccount')),
                ('cac_reg_doc', models.ImageField(max_length=255, upload_to=accounts.models.UploadHostAccountHelper('cac_reg_doc'), verbose_name='CAC Registration Document')),
                ('proof_of_address', models.ImageField(max_length=255, upload_to=accounts.models.UploadHostAccountHelper('proof_of_address'), verbose_name='Proof of Address')),
                ('rep_id', models.ImageField(max_length=255, upload_to=accounts.models.UploadHostAccountHelper('rep_id'), verbose_name='Dir./Authorized Rep. ID Number')),
            ],
            options={
                'verbose_name': 'Company Host Account',
                'verbose_name_plural': 'Company Host Accounts',
            },
            bases=('accounts.hostaccount',),
        ),
        migrations.CreateModel(
            name='HostAccountLawyer',
            fields=[
                ('hostaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.hostaccount')),
                ('nba_enrol_no', models.CharField(help_text='NBA Enrollment Number for the lawyer host.', max_length=100, unique=True, verbose_name='NBA Enrollment Number')),
                ('valid_practicing_cert', models.ImageField(max_length=255, upload_to=accounts.models.UploadHostAccountHelper('valid_practicing_cert'), verbose_name='Valid Practicing Certificate')),
                ('govt_issued_id', models.ImageField(max_length=255, upload_to=accounts.models.UploadHostAccountHelper('govt_issued_id'), verbose_name='Government Issued ID')),
                ('proof_of_address', models.ImageField(max_length=255, upload_to=accounts.models.UploadHostAccountHelper('proof_of_address'), verbose_name='Proof of Address')),
                ('ref_phone_no', models.CharField(help_text='Reference Phone Number for the lawyer host.', max_length=15, verbose_name='Reference Phone Number')),
            ],
            options={
                'verbose_name': "Lawyer's Host Account",
                'verbose_name_plural': "Lawyer's Host Accounts",
            },
            bases=('accounts.hostaccount',),
        ),
        migrations.CreateModel(
            name='HostAccountOwner',
            fields=[
                ('hostaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.hostaccount')),
            ],
            options={
                'verbose_name': 'Owner Host Account',
                'verbose_name_plural': 'Owner Host Accounts',
            },
            bases=('accounts.hostaccount',),
        ),
        migrations.CreateModel(
            name='HostAccountSurveyor',
            fields=[
                ('hostaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.hostaccount')),
                ('surcon_reg_no', models.CharField(help_text='SURCON Registration Number for the surveyor host.', max_length=100, unique=True, verbose_name='SURCON Registration Number')),
                ('practice_license', models.ImageField(max_length=255, upload_to=accounts.models.UploadHostAccountHelper('practice_license'), verbose_name='Practice License')),
                ('govt_issued_id', models.ImageField(max_length=255, upload_to=accounts.models.UploadHostAccountHelper('govt_issued_id'), verbose_name='Government Issued ID')),
                ('ref_phone_no', models.CharField(help_text='Reference Phone Number for the surveyor host.', max_length=15, verbose_name='Reference Phone Number')),
            ],
            options={
                'verbose_name': "Surveyor's Host Account",
                'verbose_name_plural': "Surveyor's Host Accounts",
            },
            bases=('accounts.hostaccount',),
        ),
        migrations.AlterModelOptions(
            name='hostaccount',
            options={},
        ),
        migrations.RemoveField(
            model_name='hostaccount',
            name='identity_image',
        ),
        migrations.RemoveField(
            model_name='hostaccount',
            name='identity_number',
        ),
        migrations.RemoveField(
            model_name='hostaccount',
            name='identity_type',
        ),
        migrations.AddField(
            model_name='hostaccount',
            name='bio',
            field=models.TextField(blank=True, help_text='A brief bio about the host.', max_length=500, verbose_name='Host Bio'),
        ),
        migrations.AddField(
            model_name='hostaccount',
            name='type',
            field=models.CharField(blank=True, choices=[('agent', 'Agent'), ('architect', 'Architect'), ('company', 'Company'), ('lawyer', 'Lawyer'), ('owner', 'Owner'), ('surveyor', 'Surveyor')], help_text='Type of host, e.g., individual, agency, etc.', max_length=100, null=True, verbose_name='Host Type'),
        ),
        migrations.AlterField(
            model_name='hostaccount',
            name='host_photo',
            field=models.ImageField(max_length=255, upload_to=accounts.models.UploadHostAccountHelper('host_photo'), verbose_name='Host Photo'),
        ),
    ]
