# Generated by Django 5.2.10 on 2026-02-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_hostaccountagent_hostaccountarchitect_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostaccount',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='hostaccount',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified'), ('rejected', 'Rejected'), ('in_review', 'In Review')], default='in_review', help_text='Verification status', max_length=100, verbose_name='Verification Status'),
        ),
        migrations.AddField(
            model_name='hostaccount',
            name='status_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Verification Status Reason'),
        ),
        migrations.AlterField(
            model_name='hostaccount',
            name='type',
            field=models.CharField(blank=True, choices=[('agent', 'Agent'), ('architect', 'Architect'), ('company', 'Company'), ('lawyer', 'Lawyer'), ('owner', 'Owner'), ('surveyor', 'Surveyor')], help_text='Type of host, e.g., lawyer, agent, etc.', max_length=100, null=True, verbose_name='Host Type'),
        ),
    ]
