# Generated by Django 5.2.10 on 2026-02-04 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_hostaccount_is_verified_hostaccount_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
