# Generated by Django 5.2.11 on 2026-02-06 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_hostaccount_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostaccount',
            options={'verbose_name': 'Host Account', 'verbose_name_plural': 'Host Accounts'},
        ),
    ]
