# Generated by Django 5.2.10 on 2026-01-07 02:34

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        VectorExtension()
    ]
