# Generated by Django 5.2.10 on 2026-01-07 08:12

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_enable_vector_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True),
        ),
    ]
