# Generated by Django 5.2.11 on 2026-02-06 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_embedding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiedproperty',
            name='is_auto_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='verifiedproperty',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_properties', to=settings.AUTH_USER_MODEL),
        ),
    ]
