# Generated by Django 5.2.11 on 2026-02-09 17:25

import django.db.models.deletion
import utilities.idx
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_verifiedproperty_is_auto_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyChat',
            fields=[
                ('id', models.CharField(default=utilities.idx.generate_property_chat_id, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Chat',
                'verbose_name_plural': 'Property Chats',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyChatMessage',
            fields=[
                ('id', models.CharField(default=utilities.idx.generate_property_chat_message_id, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='properties.propertychat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Chat Message',
                'verbose_name_plural': 'Property Chat Messages',
                'ordering': ['updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='propertychat',
            constraint=models.UniqueConstraint(fields=('property', 'client'), name='unique_property_client_chat', violation_error_message='You already have a chat with this property'),
        ),
    ]
