# Generated by Django 5.2.9 on 2025-12-30 03:57

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_bannedproperty_property'),
    ]

    operations = [
        VectorExtension()
    ]
