# Generated by Django 5.2.11 on 2026-02-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_propertychat_propertychatmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertychat',
            name='allow_payment',
            field=models.BooleanField(default=False),
        ),
    ]
