# Generated by Django 5.2.9 on 2025-12-30 09:43

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_cognito_uid'),
        ('properties', '0006_enable_vector_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AddIndex(
            model_name='property',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='property_embedding_index', opclasses=['vector_l2_ops']),
        ),
    ]
